### ISSUE TITLE
MacOS 12.4 install.esd not found

### ISSUE THREAD

**Issue by mav2287** [coreyramirezgomez/macos-iso-creator#2]
I downloaded the latest macOS installer (12.4) and tried to use this script, however I got an error that said install.esd was not found. I checked the package contents and confirmed that it was missing, however I was able to confirm that the installer was viable by creating a usb the long way with the create install media script that is built in.

**Comment by coreyramirezgomez** [comment]
I haven't been keeping up with the latest updates. Theoretically, this should still work (using createmediainstaller), but I don't have the bandwidth to maintain this anymore. Besides there are other better tools than mine.
